// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AuthController: typeof import('./src/components/AuthController.vue')['default']
    BiArrowUpRightCircle: typeof import('virtual:vite-icons/bi/arrow-up-right-circle')['default']
    BiChevronExpand: typeof import('virtual:vite-icons/bi/chevron-expand')['default']
    BxBxsMoon: typeof import('virtual:vite-icons/bx/bxs-moon')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    DiscResult: typeof import('./src/components/DiscResult.vue')['default']
    'FaSolid:sun': typeof import('virtual:vite-icons/fa-solid/sun')['default']
    'Feather:upload': typeof import('virtual:vite-icons/feather/upload')['default']
    Firework: typeof import('./src/components/Firework.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GiftResult: typeof import('./src/components/GiftResult.vue')['default']
    'GrommetIcons:google': typeof import('virtual:vite-icons/grommet-icons/google')['default']
    'HeroiconsOutline:logout': typeof import('virtual:vite-icons/heroicons-outline/logout')['default']
    'HeroiconsOutline:menuAlt2': typeof import('virtual:vite-icons/heroicons-outline/menu-alt2')['default']
    IconoirCancel: typeof import('virtual:vite-icons/iconoir/cancel')['default']
    'Jam:close': typeof import('virtual:vite-icons/jam/close')['default']
    'Jam:closeCircle': typeof import('virtual:vite-icons/jam/close-circle')['default']
    'Jam:files': typeof import('virtual:vite-icons/jam/files')['default']
    LocaleToggle: typeof import('./src/components/LocaleToggle.vue')['default']
    'Mdi:chevronRight': typeof import('virtual:vite-icons/mdi/chevron-right')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    ScrollSnap: typeof import('./src/components/ScrollSnap.vue')['default']
    ScrollSnapItem: typeof import('./src/components/ScrollSnapItem.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    'Twemoji:inboxTray': typeof import('virtual:vite-icons/twemoji/inbox-tray')['default']
    'Twemoji:openMailboxWithRaisedFlag': typeof import('virtual:vite-icons/twemoji/open-mailbox-with-raised-flag')['default']
    'Twemoji:outboxTray': typeof import('virtual:vite-icons/twemoji/outbox-tray')['default']
    TwemojiClipboard: typeof import('virtual:vite-icons/twemoji/clipboard')['default']
    TwemojiLightBulb: typeof import('virtual:vite-icons/twemoji/light-bulb')['default']
    UilEnglishToChinese: typeof import('virtual:vite-icons/uil/english-to-chinese')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
    VideoCard: typeof import('./src/components/VideoCard.vue')['default']
  }
}

export { }
