// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AuthController: typeof import('./src/components/AuthController.vue')['default']
    BiArrowUpRightCircle: typeof import('virtual:vite-icons/bi/arrow-up-right-circle')['default']
    BiChevronExpand: typeof import('virtual:vite-icons/bi/chevron-expand')['default']
    BxBxsMoon: typeof import('virtual:vite-icons/bx/bxs-moon')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    DiscResult: typeof import('./src/components/DiscResult.vue')['default']
    'FaSolid:sun': typeof import('virtual:vite-icons/fa-solid/sun')['default']
    Firework: typeof import('./src/components/Firework.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GiftResult: typeof import('./src/components/GiftResult.vue')['default']
    'GrommetIcons:google': typeof import('virtual:vite-icons/grommet-icons/google')['default']
    'HeroiconsOutline:logout': typeof import('virtual:vite-icons/heroicons-outline/logout')['default']
    'HeroiconsOutline:menuAlt2': typeof import('virtual:vite-icons/heroicons-outline/menu-alt2')['default']
    IconoirCancel: typeof import('virtual:vite-icons/iconoir/cancel')['default']
    LocaleToggle: typeof import('./src/components/LocaleToggle.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    'Twemoji:inboxTray': typeof import('virtual:vite-icons/twemoji/inbox-tray')['default']
    TwemojiClipboard: typeof import('virtual:vite-icons/twemoji/clipboard')['default']
    TwemojiGrimacingFace: typeof import('virtual:vite-icons/twemoji/grimacing-face')['default']
    TwemojiLightBulb: typeof import('virtual:vite-icons/twemoji/light-bulb')['default']
    TwemojiLink: typeof import('virtual:vite-icons/twemoji/link')['default']
    UilEnglishToChinese: typeof import('virtual:vite-icons/uil/english-to-chinese')['default']
    UserDetails: typeof import('./src/components/UserDetails.vue')['default']
  }
}

export { }
