export const disc = {
  0: {
    question: {
      a: '富于冒险:愿意面对新事物并敢于下决心掌握的人',
      b: '适应力强:轻松自如适应任何环境',
      c: '生动:充满活力,表情生动,多手势',
      d: '善于分析:喜欢研究各部分之间的逻辑和正确的关系',
    },
    answer: { a: 'd', b: 's', c: 'i', d: 'c' },
  },
  1: {
    question: {
      a: '坚持不懈：要完成现有的事才能做新的事情',
      b: '喜好娱乐：开心充满乐趣与幽默感',
      c: '善于说服：用逻辑和事实而不用威严和权利服人',
      d: '平和：在冲突中不受干扰，保持平静',
    },
    answer: { a: 'c', b: 'i', c: 'd', d: 's' },
  },
  2: {
    question: {
      a: '顺服：易接受他人的观点和喜好，不坚持己见',
      b: '自我牺牲：为他人利益愿意放弃个人意见',
      c: '善于社交：认为与人相处是好玩，而不是挑战或者商业机会',
      d: '意志坚定：决心以自己的方式做事',
    },
    answer: { a: 's', b: 'c', c: 'i', d: 'd' },
  },
  3: {
    question: {
      a: '使人认同：因人格魅力或性格使人认同',
      b: '体贴：关心别人的感受与需要',
      c: '竞争性：把一切当作竞赛，总是有强烈的赢的欲望',
      d: '自控性：控制自己的情感，极少流露',
    },
    answer: { a: 'i', b: 'c', c: 'd', d: 's' },
  },
  4: {
    question: {
      a: '使人振作：给他人清新振奋的刺激',
      b: '尊重他人：对人诚实尊重',
      c: '善于应变：对任何情况都能作出有效的反应',
      d: '含蓄：自我约束情绪与热忱',
    },
    answer: { a: 'i', b: 'c', c: 'd', d: 's' },
  },
  5: {
    question: {
      a: '生机勃勃：充满生命力与兴奋',
      b: '满足：容易接受任何情况与环境',
      c: '敏感：对周围的人事过分关心',
      d: '自立：独立性强，只依靠自己的能力、判断、与才智',
    },
    answer: { a: 'i', b: 's', c: 'c', d: 'd' },
  },
  6: {
    question: {
      a: '计划者：先做详尽的计划，并严格要计划进行，不想改动',
      b: '耐性：不因延误而懊恼，冷静且能容忍',
      c: '积极：相信自己有转危为安的能力',
      d: '推动者：动用性格魅力或鼓励别人参与',
    },
    answer: { a: 'c', b: 's', c: 'd', d: 'i' },
  },
  7: {
    question: {
      a: '肯定：自信，极少犹豫或者动摇',
      b: '无拘无束：不喜欢预先计划，或者被计划牵制',
      c: '羞涩：安静，不善于交谈',
      d: '有时间性：生活处事依靠时间表，不喜欢计划被人干扰',
    },
    answer: { a: 'd', b: 'i', c: 's', d: 'c' },
  },
  8: {
    question: {
      a: '迁就：改变自己以与他人协调，短时间内按他人要求行事',
      b: '井井有条：有系统有条理安排事情的人',
      c: '坦率：毫无保留，坦率发言',
      d: '乐观：令他人和自己相信任何事情都会好转',
    },
    answer: { a: 's', b: 'c', c: 'i', d: 'd' },
  },
  9: {
    question: {
      a: '强迫性：发号施令，强迫他人听从',
      b: '忠诚：一贯可靠，忠心不移，有时毫无根据地奉献',
      c: '有趣：风趣，幽默，把任何事物都能变成精彩的故事',
      d: '友善：不主动交谈，不爱争论',
    },
    answer: { a: 'd', b: 'c', c: 'i', d: 's' },
  },
  10: {
    question: {
      a: '勇敢：敢于冒险，无所畏惧',
      b: '体贴：待人得体，有耐心',
      c: '注意细节：观察入微，做事情有条不紊',
      d: '可爱：开心，与他人相处充满乐趣',
    },
    answer: { a: 'd', b: 's', c: 'c', d: 'i' },
  },
  11: {
    question: {
      a: '令人开心：充满活力，并将快乐传于他人',
      b: '文化修养：对艺术学术特别爱好，如戏剧、交响乐',
      c: '自信：确信自己个人能力与成功',
      d: '贯彻始终：情绪平稳，做事情坚持不懈',
    },
    answer: { a: 'i', b: 'c', c: 'd', d: 's' },
  },
  12: {
    question: {
      a: '理想主义：以自己完美的标准来设想衡量新事物',
      b: '独立：自给自足，独立自信，不需要他人帮忙',
      c: '无攻击性：不说或者做可能引起别人不满和反对的事情',
      d: '富有激励：鼓励别人参与、加入，并把每件事情变得有趣',
    },
    answer: { a: 'c', b: 'd', c: 's', d: 'i' },
  },
  13: {
    question: {
      a: '感情外露：从不掩饰情感.喜好,交谈时常身不由己接触他人',
      b: '深沉：深刻并常常内省，对肤浅的交谈、消遣会厌恶',
      c: '果断：有很快做出判断与结论的能力',
      d: '幽默：语气平和而有冷静的幽默',
    },
    answer: { a: 'i', b: 'c', c: 'd', d: 's' },
  },
  14: {
    question: {
      a: '调解者：经常居中调节不同的意见，以避免双方的冲突',
      b: '音乐性：爱好参与并有较深的鉴赏能力，因音乐的艺术性,而不是因为表演的乐趣',
      c: '发起人：高效率的推动者，是他人的领导者，闲不住',
      d: '喜交朋友：喜欢周旋聚会中，善交新朋友不把任何人当陌生人',
    },
    answer: { a: 's', b: 'c', c: 'd', d: 'i' },
  },
  15: {
    question: {
      a: '考虑周到：善解人意，帮助别人，记住特别的日子',
      b: '执着：不达目的，誓不罢休',
      c: '多言：不断的说话、讲笑话以娱乐他人，觉得应该避免沉默而带来的的尴尬',
      d: '容忍：易接受别人的想法和看法，不需要反对或改变他人',
    },
    answer: { a: 'c', b: 'd', c: 'i', d: 's' },
  },
  16: {
    question: {
      a: '聆听者：愿意听别人倾诉',
      b: '忠心对自己的理想、朋友、工作都绝对忠实，有时甚至不需要理由',
      c: '领导者：天生的领导，不相信别人的能力能比上自己',
      d: '活力充沛：充满活力，精力充沛',
    },
    answer: { a: 's', b: 'c', c: 'd', d: 'i' },
  },
  17: {
    question: {
      a: '知足：满足自己拥有的，很少羡慕别人',
      b: '首领：要求领导地位及别人跟随',
      c: '制图者：用图表数字来组织生活，解决问题',
      d: '惹人喜爱：人们注意的中心，令人喜欢',
    },
    answer: { a: 's', b: 'd', c: 'c', d: 'i' },
  },
  18: {
    question: {
      a: '完美主义者：对自己、对别人都高标准、一切事物有秩序',
      b: '和气：易相处，易说话，易让人接近',
      c: '勤劳：不停的工作，完成任务，不愿意休息',
      d: '受欢迎：聚会时的灵魂人物，受欢迎的宾客',
    },
    answer: { a: 'c', b: 's', c: 'd', d: 'i' },
  },
  19: {
    question: {
      a: '跳跃性：充满活力和生气勃勃',
      b: '无畏：大胆前进，不怕冒险',
      c: '规范性：时时坚持自己的举止合乎认同的道德规范',
      d: '平衡：稳定，走中间路线',
    },
    answer: { a: 'i', b: 'd', c: 'c', d: 's' },
  },
  20: {
    question: {
      a: '乏味：死气沉沉，缺乏生气',
      b: '忸怩：躲避别人的注意力，在众人注意下不自然',
      c: '露骨：好表现，华而不实，声音大',
      d: '专横：喜命令支配，有时略显傲慢',
    },
    answer: { a: 's', b: 'c', c: 'i', d: 'd' },
  },
  21: {
    question: {
      a: '散漫：生活任性无秩序',
      b: '无同情心：不易理解别人的问题和麻烦',
      c: '缺乏热情：不易兴奋，经常感到好事难做',
      d: '不宽恕：不易宽恕和忘记别人对自己的伤害，易嫉妒',
    },
    answer: { a: 'i', b: 'd', c: 's', d: 'c' },
  },
  22: {
    question: {
      a: '保留：不愿意参与，尤其是当事情复杂时',
      b: '怨恨：把实际或者自己想象的别人的冒犯经常放在心中',
      c: '逆反：抗拒、或者拒不接受别人的方法，固执己见',
      d: '唠叨：重复讲同一件事情或故事，忘记已经重复多次，总是不断找话题说话',
    },
    answer: { a: 's', b: 'c', c: 'd', d: 'i' },
  },
  23: {
    question: {
      a: '挑剔：坚持琐事细节，总喜欢挑不足',
      b: '胆小：经常感到强烈的担心焦虑、悲戚',
      c: '健忘：缺乏自我约束，导致健忘，不愿意回忆无趣的事情',
      d: '率直：直言不讳，直接表达自己的看法',
    },
    answer: { a: 'c', b: 's', c: 'i', d: 'd' },
  },
  24: {
    question: {
      a: '没耐性：难以忍受等待别人',
      b: '无安全感：感到担心且无自信心',
      c: '优柔寡断：很难下决定',
      d: '好插嘴：一个滔滔不绝的发言人，不是好听众，不注意别人的说话',
    },
    answer: { a: 'd', b: 's', c: 'c', d: 'i' },
  },
  25: {
    question: {
      a: '不受欢迎：由于强烈要求完美，而拒人千里',
      b: '不参与：不愿意加入，不参与，对别人生活不感兴趣',
      c: '难预测：时而兴奋，时而低落，或总是不兑现诺言',
      d: '缺同情心：很难当众表达对弱者或者受难者的情感',
    },
    answer: { a: 'c', b: 's', c: 'i', d: 'd' },
  },
  26: {
    question: {
      a: '固执：坚持照自己的意见行事，不听不同意见',
      b: '随兴：做事情没有一贯性，随意做事情',
      c: '难于取悦：因为要求太高而使别人很难取悦',
      d: '行动迟缓：迟迟才行动，不易参与或者行动总是慢半拍',
    },
    answer: { a: 'd', b: 'i', c: 'c', d: 's' },
  },
  27: {
    question: {
      a: '平淡：平实淡漠，中间路线,无高低之分，很少表露情感',
      b: '悲观：尽管期待最好但往往首先看到事物不利之处',
      c: '自负：自我评价高，认为自己是最好的人选',
      d: '放任:许别人做他喜欢做的事情，为的是讨好别人，令别人鼓吹自己',
    },
    answer: { a: 's', b: 'c', c: 'd', d: 'i' },
  },
  28: {
    question: {
      a: '易怒：善变，孩子性格，易激动，过后马上就忘了',
      b: '无目标：不喜欢目标，也无意订目标',
      c: '好争论：易与人争吵，不管对何事都觉得自己是对的',
      d: '孤芳自赏：容易感到被疏离，经常没有安全感或担心别人不喜欢和自己相处',
    },
    answer: { a: 'i', b: 's', c: 'd', d: 'c' },
  },
  29: {
    question: {
      a: '天真：孩子般的单纯，不理解生命的真谛',
      b: '消极：往往看到事物的消极面阴暗面，而少有积极的态度',
      c: '鲁莽：充满自信有胆识但总是不恰当',
      d: '冷漠：漠不关心，得过且过',
    },
    answer: { a: 'i', b: 'c', c: 'd', d: 's' },
  },
  30: {
    question: {
      a: '担忧：时时感到不确定、焦虑、心烦',
      b: '不善交际:总喜欢挑人毛病，不被人喜欢',
      c: '工作狂:为了回报或者说成就感，而不是为了完美，因而设立雄伟目标不断工作，耻于休息',
      d: '喜获认同：需要旁人认同赞赏，像演员',
    },
    answer: { a: 's', b: 'c', c: 'd', d: 'i' },
  },
  31: {
    question: {
      a: '过分敏感：对事物过分反应，被人误解时感到被冒犯',
      b: '不圆滑老练：经常用冒犯或考虑不周的方式表达自己',
      c: '胆怯：遇到困难退缩',
      d: '喋喋不休：难以自控，滔滔不绝，不能倾听别人',
    },
    answer: { a: 'c', b: 'd', c: 's', d: 'i' },
  },
  32: {
    question: {
      a: '腼腆：事事不确定，对所做的事情缺乏信心',
      b: '生活紊乱：缺乏安排生活的能力',
      c: '跋扈：冲动的控制事物和别人，指挥他人',
      d: '抑郁：常常情绪低落',
    },
    answer: { a: 's', b: 'i', c: 'd', d: 'c' },
  },
  33: {
    question: {
      a: '缺乏毅力：反复无常，互相矛盾，情绪与行动不合逻辑',
      b: '内向：活在自己的世界里，思想和兴趣放在心里',
      c: '不容忍：不能忍受他人的观点、态度和做事的方式',
      d: '无异议：对很多事情漠不关心',
    },
    answer: { a: 'i', b: 'c', c: 'd', d: 's' },
  },
  34: {
    question: {
      a: '杂乱无章：生活环境无秩序，经常找不到东西',
      b: '情绪化：情绪不易高涨，感到不被欣赏时很容易低落',
      c: '喃喃自语：低声说话，不在乎说不清楚',
      d: '喜操纵：精明处事，操纵事情，使对自己有利',
    },
    answer: { a: 'i', b: 'c', c: 's', d: 'd' },
  },
  35: {
    question: {
      a: '缓慢：行动思想均比较慢，过分麻烦',
      b: '顽固：决心依自己的意愿行事，不易被说服',
      c: '好表现：要吸引人，需要自己成为被人注意的中心',
      d: '有戒心：不易相信，对语言背后的真正的动机存在疑问',
    },
    answer: { a: 's', b: 'd', c: 'i', d: 'c' },
  },
  36: {
    question: {
      a: '孤僻：需要大量的时间独处，避开人群',
      b: '统治欲：毫不犹豫地表示自己的正确或控制能力',
      c: '懒惰：总是先估量事情要耗费多少精力，能不做最好',
      d: '大嗓门：说话声和笑声总盖过他人',
    },
    answer: { a: 'c', b: 'd', c: 's', d: 'i' },
  },
  37: {
    question: {
      a: '拖延：凡事起步慢，需要推动力',
      b: '多疑：凡事怀疑，不相信别人',
      c: '易怒：对行动不快或不能完成指定工作时易烦躁和发怒',
      d: '不专注：无法专心致志或者集中精力',
    },
    answer: { a: 's', b: 'c', c: 'd', d: 'i' },
  },
  38: {
    question: {
      a: '报复性：记恨并惩罚冒犯自己的人',
      b: '烦躁：喜新厌旧，不喜欢长时间做相同的事情',
      c: '勉强：不愿意参与或者说投入',
      d: '轻率：因没有耐心，不经思考，草率行动',
    },
    answer: { a: 'c', b: 'i', c: 's', d: 'd' },
  },
  39: {
    question: {
      a: '妥协：为避免矛盾即使自己是对的也不惜放弃自己的立场',
      b: '好批评：不断地衡量和下判断，经常考虑提出反对意见',
      c: '狡猾：精明，总是有办法达到目的',
      d: '善变：像孩子般注意力短暂，需要各种变化，怕无聊',
    },
    answer: { a: 's', b: 'c', c: 'd', d: 'i' },
  },
};

export const personality: Record<string, { en: string; 'zh-CN': string }> = {
  d: { en: 'Dominance', 'zh-CN': '支配型(D)' },
  i: { en: 'Influence', 'zh-CN': '影响型(I)' },
  s: { en: 'Compliance', 'zh-CN': '稳定型(S)' },
  c: { en: 'Steadiness', 'zh-CN': '尽责型(C)' },
};

export const gift = {
  0: '我宣告神真理的方式，有时会令固守传统的人不悦。',
  1: '我乐于负责使一群基督徒的生命得益处。',
  2: '我觉得我能使人详尽的学习圣经真理。',
  3: '我将真理有效地应用在生活中。',
  4: '我能自己发现一些新的真相或实情。',
  5: '我能用话语鼓励信心动摇，或忧虑烦恼，或灰心丧志的人。',
  6: '我能清楚地洞察真理与错谬道理的不同。',
  7: '我切望妥当管理金钱，为了可以尽力支持神的事工。',
  8: '我协助领袖脱离次要的事物，以便他们专注最重要的大事。',
  9: '我愿意帮助人减轻心灵上或身体上的痛苦。',
  10: '我很容易适应不同的文化。',
  11: '我曾带领他人信靠耶稣，决志接受救恩。',
  12: '当别人有需要时，我能大方地提供食物和住处。',
  13: '不论环境如何，我总是深信神必成就祂的应许。',
  14: '我切望说服他人努力向前，完成圣经上的目标。',
  15: '我能分辨何时是指派重大任务的时机，并委派适当的人。',
  16: '我曾【奉主的名】行神迹奇事而荣耀主的名。',
  17: '我曾【奉主的名】使病得医治。',
  18: '我会说方言。',
  19: '我曾翻译出神透过方言所赐的信息。',
  20: '我觉得自己在基督徒圈子里蛮有主导力。',
  21: '我独身而且很享受单身生活。',
  22: '我比别人先察觉到要为哪些需求祷告。',
  23: '我觉得我能在信心中为信仰被捕入狱，甚至面对死亡。',
  24: '我乐意在教会中做些特别的工作。',
  25: '我能从神接受启示有关未来发生的事。',
  26: '我乐于长期与同一群人相处，并能和他们同甘共苦。',
  27: '我能理解新约中有关教会的教导，以使教会更健全而有功效。',
  28: '我能用直觉去解决复杂的问题。',
  29: '我对事实的真相有洞察力，并往往能叫信徒知错悔改。',
  30: '我觉得能成为神的管道卸除人的自满任性并面对属灵真相。',
  31: '能准确地明辨是非，罪恶。',
  32: '为了神的圣工，我甘心乐意地奉献金钱和物品。',
  33: '察觉需要并帮助他人在服事上有果效。',
  34: '我对身体或灵性上有需要的人，有格外的怜悯。',
  35: '我觉得能学好另一种语言，为了服事不同文化的族群。',
  36: '我很乐意分享基督怎么拯救我，以致得到未信者的认同。',
  37: '我常接待人住在我家，同时不会感觉家庭生活受打扰。',
  38: '我从神领受一种特殊的信念，并深信祂会成就一件不可能的事工。',
  39: '我知道自己的方向，而且看见其他基督徒来跟从我。',
  40: '我能把所提供的构想，人力，各类资源和时间组合起来使事工更有果效。',
  41: '我曾【奉主的名】赶走污鬼。',
  42: '我曾【奉主的名】医治理失常的人。',
  43: '我曾用一种未曾学过的语言，当场向会众传讲神的信息。',
  44: '我曾翻译方言而使基督的身体得造就，勉励，安慰。',
  45: '我觉得能到一个新的地区宣讲福音，并能看见新的信徒团队产生出来。',
  46: '我独身而且对结婚没有兴趣。',
  47: '我比别的基督徒更认真地实行代祷事项。',
  48: '我不畏惧为信仰遭受身体的迫害。',
  49: '我曾有效地管理教会中琐碎的杂物。',
  50: '我曾向他人发出直接从神来的信息，是适时又紧急的。',
  51: '我能深切地认识我所服事和带领的人，他们对我也一样。',
  52: '我可以花时间专心一意研读圣经真理，并与他人分享沟通。',
  53: '我常能从多处可选择的经文中，选择一则来应用并且有果效。',
  54: '我觉得我有能力获取圣经中的新知识，而且精通其中的原则。',
  55: '我曾督促他人为他们的艰难困苦，在圣经中寻找解决之道。',
  56: '我倾向不看表面，而侦查人的动机。',
  57: '面对上帝的事工有急迫的经济需求时，我会深深被感动。',
  58: '我乐于做例行的工作，成全别人更有效的事奉。',
  59: '我很喜欢到医院或养老院探访，并在这类事工上看见果效。',
  60: '我曾和不同种族，文化，语言的基督徒相交愉快。',
  61: '我曾清楚解明耶稣是救主，而使听者有正面的响应。',
  62: '我有让陌生人在我家有宾至如归之感的诀窍。',
  63: '我十分相信神的同在和权能会成就不可能的事。',
  64: '我乐于领导，激励并鼓舞人参与主的圣工。',
  65: '我曾提出有效的计划，并有效率地完成团体的目标。',
  66: '神透过我的生命，曾多次介入一些不可能成就的事。',
  67: '我曾【奉主的名】成功地医治心灵受伤的人。',
  68: '我可以用一种未曾学过的语言向上帝说话。',
  69: '我曾祷告或许在有人说方言时，我能把它翻译出来。',
  70: '其他基督徒都会照着我说的去行，而不会提出许多异议。',
  71: '我很高兴因着单身而有更多的时间服事主。',
  72: '祷告是我最喜欢的属灵操练之一。',
  73: '深信为我的信仰而死，不是发生在我身上最糟糕的事。',
  74: '纵然我做的是一成不变的工作，只要让神得着荣耀就深觉满意。',
  75: '我深愿传讲直接从神来的信息，能造就，劝勉和安慰人。',
  76: '我曾帮助有需要的基督徒，从相关的经文中，学习如何渡过难关，并和他们一同祷告。',
  77: '我能与他人沟通圣经真理，并看见他们在知识，态度，价值观和行为上的改变。',
  78: '针对基督肢体的特殊需要，我能洞察并应用圣经真理。',
  79: '我大量地学习和研读圣经真理。',
  80: '我切望能有效地辅导那些困惑的，有罪疚感和上瘾的人。',
  81: '我能准确地分辨出哪一种教导是出自神，撒旦或人。',
  82: '我深信神会供应我的需要，因此我全心奉献钱财，在所不惜。',
  83: '当他人因我所作的得着奖赏，我觉得非常快乐。',
  84: '我乐于带独居老人，生病的人外出活动或实际关怀他们。',
  85: '我觉得我能享受在其他国家的生活。',
  86: '我切望传讲有关福音的救恩信息。',
  87: '我恳求亲切地接待来我家的人，他们也很自在欢喜。',
  88: '我确信我知道神对祂未来事工成长之特定旨意，甚至当别人还不确定的时候。',
  89: '我会影响他人去完成一项特殊任务或圣经中的某一个目标。',
  90: '我能为他人指明方向并为他们作出决定，而不是说服他们接受我的想法。',
  91: '神曾经使用我，在一些人和事物中做超自然的改变。',
  92: '我曾为他人祷告，使病得医治。',
  93: '当我公开用方言宣讲时，会期待有人把它翻译出来。',
  94: '我曾翻译过方言祷告而且似乎使人得着祝福。',
  95: '我渴望被差派出去建立教会。',
  96: '我独身而且控制性欲少有困难。',
  97: '神一直具体地响应我的祷告。',
  98: '我觉得就是面对恐怖分子给我死亡的威胁也不致动摇我的信仰。',
  99: '我能看出教会内一些需要去做的事，而且愿意主动去帮忙。',
  100: '我曾说出从神领受的警告，审判或引导的信息。',
  101: '我觉得我能把远离教会生活的基督徒挽回回来。',
  102: '我曾训练基督徒成为更顺服主基督的门徒。',
  103: '我曾在面临重大决策时，感觉神超凡的同在所带给我的信心。',
  104: '我能分辨圣经中关键和重要的事实。',
  105: '我曾安慰在苦难中的基督徒，结果他们都感觉到医治和帮助。',
  106: '我能在大家还被蒙在鼓里时，看穿一个骗子。',
  107: '为了圣工的利益，我愿意降低自己生活的水平。',
  108: '我乐意在查经班担任老师的助手。',
  109: '我乐于和独居人士或犯人愉快地谈天说地。',
  110: '我热切渴望其他国家民族的人归回信主。',
  111: '我有负担去赢取未信者归向基督。',
  112: '我很希望开放我的住家，去接待主的工人。',
  113: '每当大家信心低迷之际，我仍坚信依靠神。',
  114: '别人跟随我，因为我在造就教会全体上有专业的知识。',
  115: '为了一个团体或机构的成功，我乐于承担应负之责。',
  116: '我曾【奉主的名】使瞎眼的得看见。',
  117: '我曾成功地以超自然方式为病得医治代祷。',
  118: '每当我说方言时，我相信它会造就基督的肢体。',
  119: '我曾翻译过方言，信息就如从神直接领受的。',
  120: '教会委派我到信徒与未信者中间去行使神所赐的权柄。',
  121: '我能真正认同保罗的心愿，就是别人能像他一样守独身。',
  122: '我切望忠心地为别人的服事代祷，因为看到代祷产生的果效。',
  123: '我能认同那些受迫害的基督徒，他们绝不会为了逃避被捕入狱或者面对死亡而否认信仰。',
  124: '我总是愉快地去做别人要求我做的事，小事也没关系。',
};

export const giftEn = {
  0: 'When I speak the truth about the gospel, sometimes people with a more traditional beliefs may find it unpleasant. ',
  1: 'I’m willing to be responsible for the well-being of my cell group ',
  2: 'I think I can enable people to study the Bible in detail. ',
  3: "I am able to apply God's word effectively in life. ",
  4: 'I can discover some new truths or facts by myself. ',
  5: 'I can use my words to encourage people who are unstable, worried, troubled or discouraged in faith. ',
  6: 'I can clearly differentiate what is according to the truth and what is not. ',
  7: 'I want to cultivate good financial management so that I’m able to support God’s ministry',
  8: 'I help out leaders to handle smaller task so that they could focus on more important tasks ',
  9: 'I am willing to help people relieve their mental or physical pain. ',
  10: 'I could easily adapt to different situations/cultures',
  11: 'I have led others to believe in Jesus and accept salvation before. ',
  12: 'I can generously provide food and shelter when there is someone in need. ',
  13: 'Regardless of the circumstances, I always believe that God will fulfill his promises. ',
  14: 'I am eager to persuade others to move forward and accomplish the biblical goals. ',
  15: 'I know when it’s the right time to assign the appropriate task to the right person ',
  16: 'I have performed miracles [in the name of the Lord]. ',
  17: 'I have cured diseases [in the name of the Lord]. ',
  18: 'I can speak in tongues. ',
  19: 'I have translated the message given by God in tongues. ',
  20: 'I think I am quite dominant in the Christian circle. ',
  21: 'I am single and I enjoy my single life. ',
  22: 'I always realize what needs to be prayed before others. ',
  23: 'I am willing to be arrested, imprisoned and even facing death for my faith. ',
  24: 'I am glad to do some special work in the church. ',
  25: 'I can receive revelation from God about what will happen in the future. ',
  26: 'I am happy to get along with the same group of people for a long time, and can share my ups and downs with them. ',
  27: 'I can understand the teachings of the church in the New Testament to make the church more sound and effective. ',
  28: 'I can use intuition to solve complex problems. ',
  29: 'I have insight into the truth, and can often make believers know their mistakes and repent. ',
  30: "I think I can be a channel for God to remove people's complacency and face the spiritual truth. ",
  31: 'Able to distinguish right from wrong accurately. ',
  32: 'For the cause of God, I am willing to give money and goods. ',
  33: 'Perceive the need and help others to be effective in serving. ',
  34: 'I have special compassion for people who are in need physically or spiritually. ',
  35: 'I think I can learn another language well, in order to serve different cultural groups. ',
  36: 'I am happy to share how Christ saved me, so that I will be recognized by unbelievers. ',
  37: 'I often invite people to live in my house without feeling they disturbed my family life. ',
  38: 'I have received a special belief from God, and I am convinced that He will accomplish an impossible ministry. ',
  39: 'I know my direction and I see other Christians follow me along the way. ',
  40: 'I can combine ideas, manpower, time and various resources to make the ministry more effective. ',
  41: 'I used to drive away evil spirits [in the name of the Lord]. ',
  42: 'I have cured people who were dysfunctional [in the name of the Lord]. ',
  43: 'I used a language that I had never learned before to preach the message of God to the congregation on the spot. ',
  44: 'I have translated tongues so that the body of Christ can be built up, encouraged, and comforted. ',
  45: 'I think I can go to a new area to preach the gospel and see a new team of believers emerge. ',
  46: 'I am single and have no interest in getting married. ',
  47: 'I practice intercession matters more seriously than other Christians. ',
  48: 'I am not afraid to suffer physical persecution for my faith. ',
  49: 'I have effectively managed trivial issues in the church. ',
  50: 'I have once forward a message directly from God to others, where the message is on time and urgently needed. ',
  51: 'I can know the people I serve and lead very deeply, and they do the same to me. ',
  52: 'I can spend time studying the truth of the Bible intently and sharing it or communicating it with others. ',
  53: 'I can choose one of the many scriptures to apply in life and it will be very effective. ',
  54: 'I think I have the ability to acquire new knowledge in the Bible, and I am proficient in its principles. ',
  55: 'I have urged others to find solutions in the Bible for their difficulties. ',
  56: "I tend not to look at the surface, but to investigate people's motives. ",
  57: "When God's ministry are facing an urgent financial need, I will be deeply moved. ",
  58: "I am willing to do routine work to fulfill others' more effective ministry. ",
  59: 'I like to visit hospitals or nursing homes and see results in this type of ministry. ',
  60: 'I have had a happy friendship with Christians of different races, cultures, and languages. ',
  61: 'I have clearly explained that Jesus is the Savior before, and the listeners gave a positive response. ',
  62: 'I have a knack for making strangers feel at home in my house. ',
  63: 'I believe very much that the presence and power of God will accomplish impossible things. ',
  64: "I am willing to lead and inspire people to participate in the Lord's work. ",
  65: 'I have put forward effective plans and achieved the goals of the group efficiently. ',
  66: 'God has repeatedly intervened in impossible things through my life. ',
  67: 'I have successfully healed wounded people [in the name of the Lord]. ',
  68: 'I can speak to God in a language I have never learned. ',
  69: 'I once prayed that maybe when someone spoke in tongues, I could translate it. ',
  70: 'Other Christians will do what I say, and will not raise many objections. ',
  71: 'I am very happy to have more time to serve the Lord because I am single. ',
  72: 'Prayer is one of my favorite spiritual exercises. ',
  73: 'I am convinced that dying for my faith is not the worst thing that can happened to me. ',
  74: 'Even though what I am doing is an unchanging job, as long as I let God be glorified, I am deeply satisfied. ',
  75: 'I am deeply willing to preach a message directly from God that can edify, encourage and comfort people. ',
  76: 'I have helped Christians in need where I helped them to learn from relevant scriptures on how to overcome difficulties, and prayed with them. ',
  77: 'I can communicate biblical truths with others and see their changes in knowledge, attitudes, values, and behaviors. ',
  78: 'I can perceive the special needs of the body of Christ and apply biblical truths. ',
  79: 'I study Bible truths a lot. ',
  80: 'I hope I can effectively counsel those who are confused, guilty and addicted. ',
  81: 'I can accurately tell which kind of teaching comes from God, Satan or man. ',
  82: "I am convinced that God will provide for my needs, so I give my money wholeheartedly and don't hesitate to do it. ",
  83: 'When others are rewarded for what I have done, I feel very happy. ',
  84: 'I like to take elderly people who live alone or sick people out for activities and actually care for them. ',
  85: 'I think I can enjoy life in other countries. ',
  86: 'I am eager to preach the salvation about the gospel. ',
  87: 'I welcomed eagerly those who came to my house cordially, and they were also very happy. ',
  88: "I am sure that I know God's will for the growth of his ministry in the future, even when the others are still uncertain. ",
  89: 'I will influence others to complete a special task or a goal in the Bible. ',
  90: 'I can give directions to others and make decisions for them, instead of persuading them to accept my ideas. ',
  91: 'God used me to make supernatural changes in some people and things. ',
  92: 'I have prayed for others to heal their disease. ',
  93: 'When I preach in dialect publicly, I expect someone to translate it. ',
  94: 'I have translated prayers in tongues and it seems to be blessed. ',
  95: 'I long to be sent out to plant a church. ',
  96: 'I am single and have little difficulty in controlling my libido. ',
  97: 'God has always specifically responded to my prayers. ',
  98: 'I think even facing the threat of death by terrorists, I will not shake my faith. ',
  99: 'I can see what needs to be done in the church, and I am willing to take the initiative to help. ',
  100: 'I have given warnings, judgments or guidance that I received from God. ',
  101: 'I think I can bring back the Christians who are far from the church. ',
  102: 'I have trained Christians to become disciples who are more obedient to the Lord Christ. ',
  103: "When I was facing a major decision, I felt the confidence that God's extraordinary presence brought me. ",
  104: 'I can distinguish key and important facts in the Bible. ',
  105: 'I have comforted Christians in suffering, and they all felt healed and helped. ',
  106: 'I can see through a liar while everyone is still in the dark. ',
  107: 'For the benefit of the work, I am willing to lower my standard of living. ',
  108: "I am happy to be the teacher's assistant in the Bible study class. ",
  109: 'I like to chat happily with people living alone or prisoners. ',
  110: 'I am eager for people from other nations to come to the Lord. ',
  111: 'I have the burden to win unbelievers for Christ. ',
  112: "I really want to open up my house to welcome the Lord's workers. ",
  113: "Whenever everyone's confidence is down, I still believe and rely on God. ",
  114: 'Others follow me because I have professional knowledge in cultivating the church as a whole. ',
  115: 'For the success of a group or an organization, I am willing to take the responsibility. ',
  116: 'I used to make the blind see [in the name of the Lord]. ',
  117: 'I have successfully interceded for the healing of the sick in a supernatural way. ',
  118: 'Whenever I speak in tongues, I believe it will build up the body of Christ. ',
  119: 'I have translated dialects, and the message is as if it were received directly from God. ',
  120: 'The church appointed me to exercise the authority given by God among believers and unbelievers. ',
  121: "I can agree with Paul's wish that others can be single like him. ",
  122: 'I am eager to pray faithfully for the service of others, because I see the effects of intercession. ',
  123: 'I can agree with those Christians who are persecuted. They will never deny their faith in order to escape arrest and go to jail or face death. ',
  124: 'I always happily do what others ask me to do, even if it is just some small things. ',
};

export const giftLabels = {
  先知: [0, 25, 50, 75, 100],
  牧师: [1, 26, 51, 76, 101],
  教导: [2, 27, 52, 77, 102],
  智慧的言语: [3, 28, 53, 78, 103],
  知识的言语: [4, 29, 54, 79, 104],
  劝化: [5, 30, 55, 80, 105],
  辨别诸灵: [6, 31, 56, 81, 106],
  施舍: [7, 32, 57, 82, 107],
  帮助人: [8, 33, 58, 83, 108],
  怜悯: [9, 34, 59, 84, 109],
  宣教: [10, 35, 60, 85, 110],
  传福音: [11, 36, 61, 86, 111],
  接待: [12, 37, 62, 87, 112],
  信心: [13, 38, 63, 88, 113],
  领导: [14, 39, 64, 89, 114],
  治理: [15, 40, 65, 90, 115],
  神迹奇事: [16, 41, 66, 91, 116],
  医治: [17, 42, 67, 92, 117],
  说方言: [18, 43, 68, 93, 118],
  翻方言: [19, 44, 69, 94, 119],
  使徒: [20, 45, 70, 95, 120],
  单身: [21, 46, 71, 96, 121],
  代祷: [22, 47, 72, 97, 122],
  '舍命受苦(殉道)': [23, 48, 73, 98, 123],
  服事: [24, 49, 74, 99, 124],
};

const usersUid = {
  'Wong Hao Jun': '1KANcTSdrtRFFTVylojrgrXcfRO2',
  'chin pooikee': 'quFK8RIhbZc6rLilHwtnuV1YwCe2',
  'Kristin Pek Su-Wen': 'xM1Flb868aVoIRcrR2mTO8MLLnG3',
  'Fong Jia Shin': '4j5P8vBfrFXgXvZ1jVJMkXDUqSy2',
  'Chow Kian Lam': 'Q158kqdTIIMCbeU63vI91nJmAMX2',
  'Chew Tse Wen': 'jV2z8sNSjFVti8NHjm5TX2IdEHf2',
  NickTheWong: 'u1QbOY6C8OcZsYnCEeB2As7ncm93',
  'Goh Hui Wen': 'LLXvCJD64UYvt2a2uX9NKqK9De23',
  'Chan Cying': '14feV5YQWJSiZ2QtOwKvAVTGG3h1',
  'Cynthia Ding Chiau Wei': 'kR0Bax9L01bwWLGjxuLQazuqjGi2',
  'kayan chai': 'RRZRRiY1JtVnsNUChFTmzzljlE23',
  'Kelly Ng': 'zyxgI6HKdLeuMwt3QcmO4kgB4r93',
  'Andre Him Jian Zhi': 'Nc1Q2nSjkdTlsph5WoHy6QzWCft1',
  'MJ Mei Jing': 'nJhgdLnZ5NejIceStYWFzn4JxWy2',
  'Justin Shuck Chze Wei': 'nNevhkXDQDOCfmRUIMrv5rqbg9G3',
  'Elaine Teh': 'BtQ12v9vClSfywSBVt1xjVy520y2',
  'Yee Sook Fun': 'V9nKuGWcUMNZNeAWa6BDyvo3pOo2',
  'Suet Yee': '6yZlsPHXduU5Gz7WtDmxRy7zyqZ2',
  'Ong Sze Miq': '8SDBD0CpivPZvUHPo6do2ep5rby1',
  'Li Kar Ken': 'zOjv5W4FSSTTZXujhVb7FdumXKm1',
  'Cloud Hoh': 'UBVdNRDfg1dyPCRmuHQE7eQWqAi1',
  'Dorothea Wong': 'NhSTS3tCFkUUBKmwcTscbyO5I3x1',
  'Huey Wen Ngu': 'BalfrWK4CVfuWrQPma6DkdxlW7x1',
  'Lee Ting Chung': 'CwrwyCY9DAamykjszIR25ZG10SC3',
  'Jasmin Yeow': 'vTB3sUFL7IdozcFwyH0xY1YbJoV2',
  'En Yi': '3W5rT7asRNbiVllh5B1F52VqLeS2',
  'Yee Chee How': 'asVe7b0UpUXKC4E9gEe670GMTSy2',
  'Khoo Han Sheng': 'vhKJeIOk9LfRspvwTb3YzIpsdkY2',
  ET: 'BHPNomoQErMnBCYOZiJqUWz9jZa2',
  'Liew Yu Jing': '0QkmJHE2AfTIYwFf4467rmMqIGE2',
  'Chia Chee Hong': 'qBXuVstfKOVQjhy4VHl5rqJSY3W2',
  'Lim Shu Yi': 'Z5MFBUWjN8aZnnb6m9DTroou6rb2',
  'Csy Chin': 'FGK0tegSBmV0K1pCcF6lxT6MLoU2',
  'Marcus Lee': 'WdDqH70NNMTRYhzKeKNxDNoiCuP2',
  'Chai Jun Wai, William': 'pP4YU1eSguVzZ9cK7yzUWnCf1di1',
  'Kelvin Lim An Hong': 'uhOvbAWX03XDDoyZBxBwLAvX9Zi2',
  'Myona Hong Sook Cheng': '4MiTP979R1URzA0ZJ3x8UCsQTvw2',
  'Ng Mei Mei': 'ewJYUqY6YufButsgoxeB0pLhKax1',
  'Foo Sze Yun': 'TCNFImSjpXd9HkPKNyBa3pchymf1',
  'Lim Xin Yee': 'O0DK8X72FUYoIabCPmP2GV19R553',
  'Shawn KH': '6HyDT5EMCtXHfd7W3Ehyde66blo1',
  'Wong Yui Soon': 'iVYGxL7qBxNIdPbr2APkiEaUviL2',
  'Kenneth Lee Kar Hong': 'n90UkGLGfCRp2JNM3Nnvh2gXR253',
  'Christy Ling Xin Yan': 'EA4azazjP5eloWPmcTYdGennLsN2',
  'Chow Hwee Lu': 'hebs0KFGHYhBnwROQHCPkl0cYhB2',
  'Tracy Law': 'zx1sIlPelqbJzPjpc2ZvhMCggG72',
  Jwei: 'WX25c5xEmQURZftpMG9WXt6IeVS2',
  'Yong Shee Mun (Kate)': 'rIkMGZ9suWSZRNRZbofbpYEpbMz2',
  'Chin Pei Yueh': 'P3GfUU6b9wNaFsIRlw6N2Zgv8kJ2',
  'Ng Kok Cheng': 'WOFWxS0EjVdxedskYRQrxCy76gX2',
  'evon Loh': 'zbaFiMnPUsRrhMBsgI2xvepvJkv2',
  'Lim Mei Yee': '3D4fKDPlyfcKo4CTCCHGm9c4hVk2',
  'Loo Kai Lee': 'xQB9q8AoMIYcaEOmDLk6hdxa4tH3',
  'Yap Jia Qian': 'Y0qGe7CZBCd8w3oTxhmkPtzFsFE3',
  'yolo swager': 'eH3h7SRm29Ne04t9yQK1Ui4fDHv1',
  'Toh Kar Wei': 'RUCUKmyjIjS6XXilu9yEsMueyD52',
  'Nicole Teo Shu Ern': 'VTOCF0RWBTXoQzKljCkRXAsmRqE3',
  'Too Yu Han': 'Ybk67WUXQFU41upbc6zskqGjm852',
  'Yap Pik Xia': 'o8TdVayAq7W1QxrrFnVWpNsmFY92',
  'Nai Pui Shan': 'eIJjhS0fgITiEjqGHqEJD5s5PTI3',
  'Pang Zheng Yeong': 'mjjlWYE8g7MYJM7sM9a6Gg5ZFRJ3',
  'Lee Mei Kee': 'nYNMuJtvOJNsMSnvsjO7GdYdcWb2',
  'Soh Siau Po': 'xYFumrVp30fyYi96PYayWqgaH6I2',
  'Lim Chen Tung': 'lBKvk38AR2fuPs5JNNaVSGO9UFJ3',
  'Lim Ming Zhou': 'oEaDRGC2c7e7IzI7NxbwJ6KXcij2',
  'Lim Xin Yi': '04KQzWgLNDXiXeUIV0zPojQWTPn2',
  'Mun Callie': 'NOZNYlB94CTihW98Q3aa7qkUIHI3',
  'Goh Wei Heng': 'B8ZsneX2goMS3GZduMeIwcmqkfe2',
  'Lim Zu Yi': 'WKxG4X2LRwVejgDCZy65fAaNhys2',
  'Chang Xiang Ying': 'n43LaQMZHXZgEuShlduGbzrJ8X53',
  'Chan Yung You': 'sq5oKZlctCN6Uytt1mpzkfu6rzq1',
  'Lim Xin Ru': '9i1QD6H9BiO1UyDrlT4bxPyREgg2',
  'Wong Jien Thong': 'YkSoWIUVDpaIwkYpm3k5VNsDZGB3',
  'Chan Mun Lik': 'Xv3puObpa7VbCeZFS7KrB5MkbaH2',
  'Wong Kar Shean': 'tLaXYrMZDtP1Vp7xLUV80oov7YF3',
  'Jenny Then Tzu Ying': 'npSw4EC6aZSVVkt4YQvQzE2qxXz2',
  'Loke Sim': 'tNVu4N5QlwWsDONXDEpsjaEtmLq2',
  'Jazz Toh': '5NOqzGumTJbdNTDWflHzLnMLnj93',
  'Goh Cheng Hao': 'mv8nlGz5qJaeToMYZ8EXdWviRP83',
  'Law Jia Yang': 'Xv3puObpa7VbCeZFS7KrB5MkbaH2',
};
